### ISSUE TITLE
ping command injection

### ISSUE THREAD

**Issue by SimonCommits** [matrizzo/cs412-project#13]
https://github.com/matrizzo/cs412-project/blob/7d3fc827a5c7bb4276fdbfe53e651f3d68a58538/src/session.cpp#L280

How:
                ping 127.0.0.1;gnome-calculator
Why:
A check is done on the hostname in executePing in src/session.cpp:
        host.find_first_not_of("abcdefghijklmnopqrstuvwxyz0123456789.-;"). But it accepts semicolons.
After that ping is executed like this: popen(("ping -c 1 " + host + " 2>&1").c_str(), "r"), pclose)
Thus when we send ping 127.0.0.1;gnome-calculator to the server it is like we execute:
        ping -c 1 127.0.0.1;gnome-calculator 2>&1
Which means that this will execute a ping followed by an opening of a gnome-calculator.

**Comment by lromerio** [comment]
This is a duplicate of #1
