### ISSUE TITLE
ls command injection

### ISSUE THREAD

**Issue by SimonCommits** [matrizzo/cs412-project#14]
https://github.com/matrizzo/cs412-project/blob/7d3fc827a5c7bb4276fdbfe53e651f3d68a58538/src/session.cpp#L306-L307

What: Opening a calculator / command injection
Where: https://github.com/matrizzo/cs412-project
How:
        login KevinMitnick
        pass FreeKevin
        mkdir whatever|gnome-calculator
        cd whatever|gnome-calculator
        ls
Why:
        mkdir and cd go without problem. But the problem happens when we are in the
        "whatever|gnome-calculator" and we do ls. Which literally executes ls -l whatever|gnome-calculator in the function executeLs of the src/session.cpp source file.

**Comment by lromerio** [comment]
This is a duplicate of #5
