### ISSUE TITLE
Command injection in ping command

### ISSUE THREAD

**Issue by PizzaWhisperer** [matrizzo/cs412-project#17]
After running `make`, launch the server with `./bin/server`.

Then launch the client with `./bin/client 127.0.0.1 1337` and feed it with 
```
ping stuff;xcalc
```
which pops a calc on the server side.
Indeed at this line https://github.com/matrizzo/cs412-project/blob/master/src/session.cpp#L284 the user input is not escaped.

**Comment by lromerio** [comment]
This is a duplicate of #1
