### ISSUE TITLE
[DUP] Command Injection in grass::Session::executePing()

### ISSUE THREAD

**Issue by hazimeh** [matrizzo/cs412-project#6]
This is a duplicate report to Issue #1, but serves to point out where the bug exists in the code.

A command injection vulnerability exists in `grass::Session::executePing()`, at _session.cpp:288_, where a user-controlled input is fed directly into a shell interpreter. Despite the attempt at sanitizing the input on line 280, the developers wrote a “typo” in the allowed characters for the host name, and white-listed the semi-colon “;” instead of the colon “:”.

Simply supplying a host name of “;gnome-calculator” or “;bash” would result in launching a calculator or a shell.

[sploit_4.zip](https://github.com/matrizzo/cs412-project/files/3172029/sploit_4.zip)

**Comment by lromerio** [comment]
As pointed out this is a duplicate of #1
